[package]
name = "haunti-core"
version = "0.8.1"
edition = "2021"
authors = ["Haunti Team <dev@haunti.ai>"]
license = "AGPL-3.0"
repository = "https://github.com/haunti-ai/core"
description = "Decentralized AI protocol on Solana with ZKML/FHE integration"
documentation = "https://docs.haunti.ai/rust"

[features]
default = ["solana-program/entrypoint", "gpu-acceleration"]
gpu-acceleration = ["cuda", "fhe-rs/cuda", "plonky3/cuda"]
testnet = ["solana-program/testnet", "anchor-lang/testnet"]
mainnet = ["solana-program/mainnet", "anchor-lang/mainnet"]
benchmark = ["criterion", "solana-bench-utils"]

[dependencies]
# Solana Core
solana-program = { version = "1.18.2", features = ["program", "borsh"] }
anchor-lang = { version = "0.29.2", features = ["init-space", "zero-copy"] }
anchor-spl = { version = "0.29.2" }
solana-zkutil = { git = "https://github.com/solana-labs/zkutil", rev = "v0.6.3" }

# Cryptography
fhe-rs = { version = "0.24.0", features = ["serde", "nightly"], git = "https://github.com/tfhe-rs/tfhe-rs" }
ark-circom = { git = "https://github.com/arkworks-rs/circom-compat", rev = "a3d4f5e" }
ark-bls12-381 = { version = "0.4.1", features = ["curve"] }
merlin = { version = "3.0.0", features = ["transcript"] }

# ZKML
plonky3 = { version = "0.1.5", features = ["parallel", "gpu"] }
circuit-benchmark = { git = "https://github.com/zk-ml/circuit-benchmark", tag = "v0.5.0" }
halo2-proofs = { git = "https://github.com/privacy-scaling-explorations/halo2", rev = "9d137b4" }

# GPU Acceleration
cuda = { version = "0.1.5", optional = true }
rustacuda = { version = "0.2.1", features = ["device"] }

# Data Handling
borsh = "0.10.3"
serde = { version = "1.0.193", features = ["derive"] }
serde_json = "1.0.108"
arrayref = "0.3.7"

# Utils
thiserror = "1.0.50"
log = "0.4.20"
solana-logger = { version = "1.18.2", features = ["log"] }
lazy_static = "1.4.0"
memmap2 = "0.9.0"

[dev-dependencies]
solana-program-test = "1.18.2"
solana-sdk = "1.18.2"
criterion = { version = "0.5.1", optional = true }
proptest = { version = "1.3.1", features = ["std"] }
arbitrary = { version = "1.3.0", features = ["derive"] }

[build-dependencies]
solana-version = "1.18.2"
rustc_version = "0.4.0"

[profile.release]
lto = "fat"
codegen-units = 1
opt-level = 3
panic = "abort"
incremental = false
strip = "symbols"

[profile.bench]
opt-level = 3
debug = false
lto = "thin"

[profile.test]
opt-level = 1
debug = true

[workspace]
members = [
    "programs/haunti-core",
    "programs/model-nft",
    "programs/token-vault",
    "zk-circuits"
]
resolver = "2"
exclude = ["legacy", "experimental"]
